services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NOVITA_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: MIDNIGHT_ROSE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true 